name: RNA-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bowtie2
  - samtools
  - bedtools
  - bbmap
  - trimmomatic
  - fastqc
  - seqtk
  - kallisto
  - spades
  - multiqc
  - numpy
  - matplotlib
  - pysam
  - checkm-genome
  - prokka
  - blast
  - busco
  - augustus
  - hmmer
  


