#!/bin/bash

curl -L https://ndownloader.figshare.com/files/24079268 -o 45R1.fastq.gz
curl -L https://ndownloader.figshare.com/files/24079271 -o 45R2.fastq.gz
curl -L https://ndownloader.figshare.com/files/24079274 -o 17R1.fastq.gz
curl -L https://ndownloader.figshare.com/files/24079280 -o 17R2.fastq.gz
curl -L https://ndownloader.figshare.com/files/24079283 -o 41R1.fastq.gz
curl -L https://ndownloader.figshare.com/files/24079289 -o 41R2.fastq.gz
curl -L https://ndownloader.figshare.com/files/24079301 -o 84R1.fastq.gz
curl -L https://ndownloader.figshare.com/files/24079304 -o 84R2.fastq.gz
curl -L https://ndownloader.figshare.com/files/24079307 -o P3R1.fastq.gz
curl -L https://ndownloader.figshare.com/files/24079310 -o P3R2.fastq.gz
curl -L https://ndownloader.figshare.com/files/24079313 -o RBYR1.fastq.gz
curl -L https://ndownloader.figshare.com/files/24079316 -o RBYR2.fastq.gz
curl -L https://ndownloader.figshare.com/files/24125876 -o S288C_reference_genome
curl -L https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/146/045/GCF_000146045.2_R64/GCF_000146045.2_R64_genomic.fna.gz -o reference_genome
