#!/bin/bash

curl -L https://figshare.com/articles/dataset/CW_45_4_S178_L002_R1_001_fastq_gz/12611465 -o 45R1.fastq.gz
curl -L https://figshare.com/articles/dataset/45R2/12611471 -o 45R2.fastq.gz
curl -L https://figshare.com/articles/dataset/17R1/12611480 -o 17R1.fastq.gz
curl -L https://figshare.com/articles/dataset/Untitled_Item/12611489 -o 17R2.fastq.gz
curl -L https://figshare.com/articles/dataset/41R1/12612377 -o 41R1.fastq.gz
curl -L https://figshare.com/articles/dataset/41R2/12612386 -o 41R2.fastq.gz
curl -L https://figshare.com/articles/dataset/84R1/12612389 -o 84R1.fastq.gz
curl -L https://figshare.com/articles/dataset/84R2/12612392 -o 84R2.fastq.gz
curl -L https://figshare.com/articles/dataset/P3R1/12612395 -o P3R1.fastq.gz
curl -L https://figshare.com/articles/dataset/P3R2/12612398 -o P3R2.fastq.gz
curl -L https://figshare.com/articles/dataset/RBYR1/12612404 -o RBYR1.fastq.gz
curl -L https://figshare.com/articles/dataset/RBYR2/12612407 -o RBYR2.fastq.gz
curl -L https://ndownloader.figshare.com/files/24125876 -o S288C_reference_genome
curl -L https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/146/045/GCF_000146045.2_R64/GCF_000146045.2_R64_genomic.fna.gz -o reference_genome.fna.gz
